# Config TOML
[urls]
apps = "https://apprenda-bluemix-api.mybluemix.net/api/v1/apps"
bind = "https://apprenda-bluemix-api.mybluemix.net/api/v1/bind"
unbind = "https://apprenda-bluemix-api.mybluemix.net/api/v1/unbind"
scale = "https://apprenda-bluemix-api.mybluemix.net/api/v1/scale"
